define(["../logic/mainpage"],function(pluginClass){
    return {
        pluginClass:pluginClass,
        style:{
            backgroundColor:"#f0f4f6"
        },
        root:["tabbar"],
        components:{
          tabbar:{
            type:"tabbarview",
            style:{
              flex:1
            },
            tabbarStyle:{
              position:"absolute",
              width:"100%",
              bottom:"0px",
              left:"0px",
              height:"50px",
              backgroundColor:"#000"             
            },
            root:[
              "mytodo","mydoing","mydone","notice","seemore"
            ]
          },
          mytodo:{
            type:"icon",
            selectedClassName:"yy-tabbar-item-selected",
            textPos:"bottom",
            font:"FontAwesome_f044",
            text:"我的待办",
            iconStyle:{
              marginTop:"5px",
              fontSize:"20px"
            },
            textStyle:{
              marginTop:"2px",
              fontSize:"14px",              
            },
            style:{
              flex:1,
              height:"44px",
              justifyContent:"center",
              alignItems:"center"
            }
          },
          mydoing:{
            type:"icon",
            textPos:"bottom",
            selectedClassName:"yy-tabbar-item-selected",
            font:"FontAwesome_f045",
            text:"我的在办",
            iconStyle:{
              marginTop:"5px",
              fontSize:"20px"
            },
            textStyle:{
              marginTop:"2px",
              fontSize:"14px"
            },
            style:{
              flex:1,
              height:"44px",
              justifyContent:"center",
              alignItems:"center"
            }
          },
          mydone:{
            type:"icon",
            textPos:"bottom",
            selectedClassName:"yy-tabbar-item-selected",
            font:"FontAwesome_f046",
            text:"我的已办",
            iconStyle:{
              marginTop:"5px",
              fontSize:"20px"
            },
            textStyle:{
              marginTop:"2px",
              fontSize:"14px"
            },
            style:{
              flex:1,
              height:"44px",
              justifyContent:"center",
              alignItems:"center"
            }
          },
          notice:{
            type:"icon",
            textPos:"bottom",
            selectedClassName:"yy-tabbar-item-selected",
            font:"FontAwesome_f086",
            text:"公告",
            iconStyle:{
              marginTop:"5px",
              fontSize:"20px"
            },
            textStyle:{
              marginTop:"2px",
              fontSize:"14px"
            },
            style:{
              flex:1,
              height:"44px",
              justifyContent:"center",
              alignItems:"center"
            }
          },
          seemore:{
            type:"icon",
            textPos:"bottom",
            selectedClassName:"yy-tabbar-item-selected",
            font:"FontAwesome_f007",
            text:"更多",
            iconStyle:{
              marginTop:"5px",
              fontSize:"20px"
            },
            textStyle:{
              marginTop:"2px",
              fontSize:"14px"
            },
            style:{
              flex:1,
              height:"44px",
              justifyContent:"center",
              alignItems:"center"
            }
          }
        }
    };
});
